// Code generated by agenttool-gen. DO NOT EDIT.
// source: internal/service

package tool

import (
	"context"
	"encoding/json"
	"fmt"

	eino_tool "github.com/cloudwego/eino/components/tool"
	"github.com/cloudwego/eino/schema"
	"github.com/MrLuoooooo/MrLuoooooagent/internal/service"
)


// CountWordsTool —— @agenttool 自动生成
type CountWordsTool struct {
	svc *service.AgentToolDemoService
}

func (t *CountWordsTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	return &schema.ToolInfo{
		Name: "demo_count_words",
		Desc: "统计文本中单词数量。测试int返回类型。",
		ParamsOneOf: schema.NewParamsOneOfByParams(map[string]*schema.ParameterInfo{
			"text": {
				Type:     schema.String,
				Desc:     "要统计的文本",
				Required: true,
			},
		}),
	}, nil
}

func (t *CountWordsTool) InvokableRun(ctx context.Context, argsJSON string, opts ...eino_tool.Option) (string, error) {
	var args struct {
		Text string `json:"text"`
	}
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return "", fmt.Errorf("demo_count_words: parse args: %w", err)
	}
	result, err := t.svc.CountWords(ctx, args.Text)
	if err != nil {
		return "", err
	}
	b, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("demo_count_words: marshal result: %w", err)
	}
	return string(b), nil
}

// ProvideCountWordsTool 供 Fx DI 使用，内部自动调用 Register
func ProvideCountWordsTool(svc *service.AgentToolDemoService) Tool {
	t := &CountWordsTool{svc: svc}
	Register(t)
	return t
}

var _ eino_tool.InvokableTool = (*CountWordsTool)(nil)

// EchoTool —— @agenttool 自动生成
type EchoTool struct {
	svc *service.AgentToolDemoService
}

func (t *EchoTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	return &schema.ToolInfo{
		Name: "demo_echo",
		Desc: "回显消息，添加Agent前缀。测试string返回类型。",
		ParamsOneOf: schema.NewParamsOneOfByParams(map[string]*schema.ParameterInfo{
			"message": {
				Type:     schema.String,
				Desc:     "要回显的消息",
				Required: true,
			},
		}),
	}, nil
}

func (t *EchoTool) InvokableRun(ctx context.Context, argsJSON string, opts ...eino_tool.Option) (string, error) {
	var args struct {
		Message string `json:"message"`
	}
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return "", fmt.Errorf("demo_echo: parse args: %w", err)
	}
	result, err := t.svc.Echo(ctx, args.Message)
	if err != nil {
		return "", err
	}
	return result, nil
}

// ProvideEchoTool 供 Fx DI 使用，内部自动调用 Register
func ProvideEchoTool(svc *service.AgentToolDemoService) Tool {
	t := &EchoTool{svc: svc}
	Register(t)
	return t
}

var _ eino_tool.InvokableTool = (*EchoTool)(nil)

// LogTool —— @agenttool 自动生成
type LogTool struct {
	svc *service.AgentToolDemoService
}

func (t *LogTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	return &schema.ToolInfo{
		Name: "demo_log",
		Desc: "记录一条日志。测试仅error返回（无返回值）。",
		ParamsOneOf: schema.NewParamsOneOfByParams(map[string]*schema.ParameterInfo{
			"message": {
				Type:     schema.String,
				Desc:     "日志内容",
				Required: true,
			},
			"level": {
				Type:     schema.String,
				Desc:     "日志级别 (info/warn/error)",
				Required: false,
			},
		}),
	}, nil
}

func (t *LogTool) InvokableRun(ctx context.Context, argsJSON string, opts ...eino_tool.Option) (string, error) {
	var args struct {
		Message string `json:"message"`
		Level string `json:"level"`
	}
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return "", fmt.Errorf("demo_log: parse args: %w", err)
	}
	if err := t.svc.Log(ctx, args.Message, args.Level); err != nil {
		return "", err
	}
	return "{}", nil
}

// ProvideLogTool 供 Fx DI 使用，内部自动调用 Register
func ProvideLogTool(svc *service.AgentToolDemoService) Tool {
	t := &LogTool{svc: svc}
	Register(t)
	return t
}

var _ eino_tool.InvokableTool = (*LogTool)(nil)

// MatchTool —— @agenttool 自动生成
type MatchTool struct {
	svc *service.AgentToolDemoService
}

func (t *MatchTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	return &schema.ToolInfo{
		Name: "demo_match",
		Desc: "检查文本是否包含关键词。测试bool返回类型。",
		ParamsOneOf: schema.NewParamsOneOfByParams(map[string]*schema.ParameterInfo{
			"text": {
				Type:     schema.String,
				Desc:     "要检查的文本",
				Required: true,
			},
			"keyword": {
				Type:     schema.String,
				Desc:     "关键词",
				Required: true,
			},
		}),
	}, nil
}

func (t *MatchTool) InvokableRun(ctx context.Context, argsJSON string, opts ...eino_tool.Option) (string, error) {
	var args struct {
		Text string `json:"text"`
		Keyword string `json:"keyword"`
	}
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return "", fmt.Errorf("demo_match: parse args: %w", err)
	}
	result, err := t.svc.Match(ctx, args.Text, args.Keyword)
	if err != nil {
		return "", err
	}
	b, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("demo_match: marshal result: %w", err)
	}
	return string(b), nil
}

// ProvideMatchTool 供 Fx DI 使用，内部自动调用 Register
func ProvideMatchTool(svc *service.AgentToolDemoService) Tool {
	t := &MatchTool{svc: svc}
	Register(t)
	return t
}

var _ eino_tool.InvokableTool = (*MatchTool)(nil)

// SplitTool —— @agenttool 自动生成
type SplitTool struct {
	svc *service.AgentToolDemoService
}

func (t *SplitTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	return &schema.ToolInfo{
		Name: "demo_split",
		Desc: "按分隔符切分字符串。测试[]string数组返回。",
		ParamsOneOf: schema.NewParamsOneOfByParams(map[string]*schema.ParameterInfo{
			"text": {
				Type:     schema.String,
				Desc:     "要切分的文本",
				Required: true,
			},
			"sep": {
				Type:     schema.String,
				Desc:     "分隔符",
				Required: false,
			},
		}),
	}, nil
}

func (t *SplitTool) InvokableRun(ctx context.Context, argsJSON string, opts ...eino_tool.Option) (string, error) {
	var args struct {
		Text string `json:"text"`
		Sep string `json:"sep"`
	}
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return "", fmt.Errorf("demo_split: parse args: %w", err)
	}
	result, err := t.svc.Split(ctx, args.Text, args.Sep)
	if err != nil {
		return "", err
	}
	b, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("demo_split: marshal result: %w", err)
	}
	return string(b), nil
}

// ProvideSplitTool 供 Fx DI 使用，内部自动调用 Register
func ProvideSplitTool(svc *service.AgentToolDemoService) Tool {
	t := &SplitTool{svc: svc}
	Register(t)
	return t
}

var _ eino_tool.InvokableTool = (*SplitTool)(nil)

