// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/MrLuoooooo/MrLuoooooagent",
        "contact": {
            "name": "MrLuoooooo",
            "url": "https://github.com/MrLuoooooo/MrLuoooooagent"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/approvals": {
            "get": {
                "description": "获取所有审批项（包含已处理和待处理的）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "审批"
                ],
                "summary": "列出全部审批项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ApprovalItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/approvals/pending": {
            "get": {
                "description": "获取所有待审批的定时任务操作。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "审批"
                ],
                "summary": "列出待审批项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ApprovalItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/approvals/{approval_id}/decide": {
            "post": {
                "description": "接受或拒绝一个待审批的定时任务操作。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "审批"
                ],
                "summary": "审批决策",
                "parameters": [
                    {
                        "type": "string",
                        "description": "审批项 ID",
                        "name": "approval_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "决策（accept=true 接受，false 拒绝）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "accept": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/batch": {
            "post": {
                "description": "并行执行最多 10 个子任务，通过 SSE 流式推送进度。每个任务独立运行，结果汇总返回。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "批量任务"
                ],
                "summary": "批量执行任务",
                "parameters": [
                    {
                        "description": "批量任务请求（最多 10 个任务）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE 流式推送 task_start/task_done/task_error/summary/done 事件"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/chat": {
            "post": {
                "description": "发送一条消息给 AI，支持普通 RAG 和 Agent 模式，支持流式和非流式返回。流式模式通过 SSE 推送 token/tool_call/tool_result 事件。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天"
                ],
                "summary": "发送聊天消息",
                "parameters": [
                    {
                        "description": "聊天请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "流式响应（SSE），由 Server-Sent Events 推送 token/tool_call/tool_result/done 事件"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/conversations": {
            "get": {
                "description": "获取所有对话会话列表。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "列出会话",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ListConversationsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的对话会话，返回会话 ID。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "创建会话",
                "parameters": [
                    {
                        "description": "会话标题（可选，默认'新会话'）",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.CreateConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.CreateConversationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除所有对话会话及其消息（不可恢复）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "清空所有会话",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/conversations/{conversation_id}": {
            "delete": {
                "description": "删除指定会话及其所有消息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "删除会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "conversation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.DeleteConversationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/conversations/{conversation_id}/messages": {
            "get": {
                "description": "获取指定会话的消息历史记录。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "获取消息历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "conversation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.GetMessagesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/documents": {
            "get": {
                "description": "获取所有已上传的文档列表。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档"
                ],
                "summary": "列出文档",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ListDocumentsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "上传文档文件（.pdf/.txt/.md），自动进行分块、向量化并存入知识库。最大 10MB。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档"
                ],
                "summary": "上传文档",
                "parameters": [
                    {
                        "type": "file",
                        "description": "上传文件（支持 .pdf / .txt / .md）",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.UploadDocumentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/documents/{document_id}": {
            "delete": {
                "description": "按文档 ID 删除已上传的文档及其向量索引。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档"
                ],
                "summary": "删除文档",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文档 ID",
                        "name": "document_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.DeleteDocumentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/models": {
            "get": {
                "description": "获取所有可用模型列表。包含配置中的预置模型和用户自定义模型，标记当前活跃模型。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型"
                ],
                "summary": "列出可用模型",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.modelItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "添加一个自定义 LLM 模型到可用模型列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型"
                ],
                "summary": "添加自定义模型",
                "parameters": [
                    {
                        "description": "自定义模型配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.ModelEntry"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/models/switch": {
            "post": {
                "description": "运行时切换 LLM 模型，无需重启服务。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型"
                ],
                "summary": "切换模型",
                "parameters": [
                    {
                        "description": "模型名称",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "model": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/models/{name}": {
            "delete": {
                "description": "从可用模型列表中删除一个自定义模型。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型"
                ],
                "summary": "删除自定义模型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模型名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/skills": {
            "get": {
                "description": "获取所有用户自定义技能列表。技能会在 Agent 运行时注入到系统提示词中。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "技能"
                ],
                "summary": "列出技能",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "添加或更新一个用户自定义技能。技能会在 Agent 执行时自动注入提示词。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "技能"
                ],
                "summary": "添加/更新技能",
                "parameters": [
                    {
                        "description": "技能配置（name + prompt）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SkillEntry"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/skills/{name}": {
            "delete": {
                "description": "按名称删除一个用户自定义技能。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "技能"
                ],
                "summary": "删除技能",
                "parameters": [
                    {
                        "type": "string",
                        "description": "技能名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/workspace": {
            "get": {
                "description": "获取当前 Agent 工作目录路径。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "获取工作目录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "设置 Agent 的当前工作目录。路径不存在时会自动创建。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "设置工作目录",
                "parameters": [
                    {
                        "description": "新的工作目录路径",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "path": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/workspace/dir": {
            "get": {
                "description": "列出指定目录下的文件和子目录（仅一层，不递归）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "列出目录内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目录路径（默认当前工作目录）",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/workspace/drives": {
            "get": {
                "description": "列出 Windows 系统上的所有可用磁盘驱动器。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "列出磁盘驱动器",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        },
        "/workspace/tree": {
            "get": {
                "description": "以树形结构返回指定目录的内容（递归，默认深度 3 层）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "返回目录树",
                "parameters": [
                    {
                        "type": "string",
                        "description": "起始目录路径（默认当前工作目录）",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.FileNode"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.ModelEntry": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "chat_model": {
                    "type": "string"
                },
                "embedding_model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "handler.FileNode": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.FileNode"
                    }
                },
                "is_dir": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "handler.modelItem": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "is_custom": {
                    "type": "boolean"
                },
                "is_local": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "model.APIEnvelope": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ApprovalItem": {
            "type": "object",
            "properties": {
                "action_type": {
                    "description": "brief description of the action",
                    "type": "string"
                },
                "approved_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "full_output": {
                    "description": "complete agent output for review",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "prompt": {
                    "description": "the original prompt that triggered this",
                    "type": "string"
                },
                "reason": {
                    "description": "why approval is needed",
                    "type": "string"
                },
                "risk_level": {
                    "description": "低/中/高",
                    "type": "string"
                },
                "source": {
                    "description": "\"cron\" / \"chat\"",
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.ApprovalStatus"
                },
                "task_name": {
                    "description": "cron job name or conversation ID",
                    "type": "string"
                }
            }
        },
        "model.ApprovalStatus": {
            "type": "string",
            "enum": [
                "pending",
                "accepted",
                "rejected",
                "expired"
            ],
            "x-enum-varnames": [
                "ApprovalPending",
                "ApprovalAccepted",
                "ApprovalRejected",
                "ApprovalExpired"
            ]
        },
        "model.BatchRequest": {
            "type": "object",
            "required": [
                "tasks"
            ],
            "properties": {
                "agent": {
                    "type": "boolean"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BatchTask"
                    }
                }
            }
        },
        "model.BatchTask": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                }
            }
        },
        "model.ChatRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "agent": {
                    "type": "boolean"
                },
                "conversation_id": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                }
            }
        },
        "model.ChatResponseData": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "model.ConversationItem": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "message_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.CreateConversationRequest": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "model.CreateConversationResponse": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.DeleteConversationResponse": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string"
                }
            }
        },
        "model.DeleteDocumentResponse": {
            "type": "object",
            "properties": {
                "document_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.DocumentItem": {
            "type": "object",
            "properties": {
                "chunk_count": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "document_id": {
                    "type": "string"
                }
            }
        },
        "model.FunctionCall": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.GetMessagesResponse": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MessageItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.ListConversationsResponse": {
            "type": "object",
            "properties": {
                "conversations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConversationItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.ListDocumentsResponse": {
            "type": "object",
            "properties": {
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DocumentItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.MessageItem": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ToolCall"
                    }
                }
            }
        },
        "model.ToolCall": {
            "type": "object",
            "properties": {
                "function": {
                    "$ref": "#/definitions/model.FunctionCall"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.UploadDocumentResponse": {
            "type": "object",
            "properties": {
                "chunk_count": {
                    "type": "integer"
                },
                "document_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "service.SkillEntry": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "4.1.2",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GoAgent Pro API",
	Description:      "AI Agent 后端系统。让大模型安全操控本地开发环境——读写文件、执行命令、联网搜索、查询股票、检索知识库。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
